TESTING: False
DEBUG: True
SECRET_KEY: b'_5#y2L"F4Q8z\n\xec]/'
MYSQL_USERNAME: 'id7241580_bcf1'
MYSQL_PASSWORD: 'wds19651'
MYSQL_DATABASE: 'id7241580_main'
MYSQL_HOST: 'reparative-twig.000webhostapp.com'


