TESTING: False
DEBUG: True
SECRET_KEY: b'_5#y2L"F4Q8z\n\xec]/'

MYSQL_USERNAME: 'b6e1da88695842'
MYSQL_PASSWORD: '13ef074bb5ae1e4'
MYSQL_DATABASE: 'heroku_5470ca94133a4e9'
MYSQL_HOST: 'eu-cdbr-west-02.cleardb.net'